### ISSUE TITLE
hippie-swagger depends on hippie being installed by parent

### ISSUE THREAD

**Issue by toshi38** [CacheControl/hippie-swagger#13]
Is there some reason that in order to use hippie swagger we need to install hippie separately?

ie I need to do both:

```
npm install hippie-swagger --save-dev
npm install hippie --save-dev
```

Why not just have it as a dependency?

Happy to fix it if someone agrees with me :)

**Comment by CacheControl** [comment]
@toshi38 Initially I was thinking of this project as a plugin for hippie, which is why it is listed as a peer dependency....however your issue has made me rethink that position.  I think it's a safe bet that most people who use this project don't have an existing hippie install, and it's probably annoying that they need to run an extra command.

Since you offered, if you'd like to move hippie into the dependencies list, I'll happily merge it.  I'll also probably release this as a major version, to prevent issues with anyone having to reconcile their existing version of hippie with whatever we peg as current.

thanks for raising this!
