### ISSUE TITLE
invalid handling of data-types

### ISSUE THREAD

**Issue by netzkind** [CacheControl/hippie-swagger#29]
**Affected Versions:** >= 3.1.0

HippieSwagger 3.1.0 brings an updated version of ajv, which in turn no longer accepts all "format"-values for datatypes.

**Excerpt from a valid Swagger-file:**
```
      price:
        type: number
        format: float
        description: Actual Price with Reduction included
        x-example: 19.99
```
According to SwaggerSpecification, the beforementioned excerpt is valid (see https://swagger.io/specification/#data-types-13).
Specifically

> OAS uses several known formats to define in fine detail the data type being used. However, to support documentation needs, the format property is an open string-valued property, and **can have any value. Formats such as "email", "uuid", and so on, MAY be used even though undefined by this specification**.
(emphasize mine)

**Expected behaviour:**
This is valid.

**Actual behaviour:**
`
Uncaught Error: unknown format "float" is used in schema at path "#/properties/price"
`

**Background:** 
with HippieSwagger 3.0.0 an prior, the "bundled" ajv raised these as a warning.
Starting with 3.1.0 of HippieSwagger, ajv raises these as an error.

**Solution:**
either 
- downgrade ajv
- remove 3.1.0 and have it 4.0.0 instead
- or instruct ajv to ignore unknown formats (see "unknownFormats" in https://github.com/epoberezkin/ajv#user-content-validation-and-reporting-options)

**Comment by CacheControl** [comment]
@netzkind thanks for filing.  I've reproduced and should have a fix shortly.

**Comment by netzkind** [comment]
@cachecontrol thank you for the fast fix,  but I am not sure if this suffices: According to spec, ANY value is valid as "format". 
So I think a fix would be to either refrain from whitelisting and go full-on "anything is allowed" (unknownFormats: "ignore") OR allow for extension of the whitelisting at runtime / during initialization. 

The latter would be my personal favorite, as it still does some validation (typos etc) while also allowing for project-specific formats.  If necessary, I might be able to provide code for this in the next week or so.

**Comment by CacheControl** [comment]
@netzkind I agree, this probably could use a follow-up PR to properly support the spec, and I like your idea of allowing additional extensions to the white-list by way of an option.  

Right now the unknown formats are stored in a [dedicated file](https://github.com/CacheControl/hippie-swagger/blob/master/lib/unknown-formats.js), but that array easily be eliminated and moved to the [settings](https://github.com/CacheControl/hippie-swagger/blob/master/lib/settings.js#L6-L12), which would automatically allow user override.  Maybe we call the option `customFormats`, and have it simply _appended_ to the default array (I can't think of any case why someone would want to _remove_ one of the formats from the list, since they are official swagger formats).  Finally, in [responses.js](https://github.com/CacheControl/hippie-swagger/blob/74fa0280a444b78343d42f0f254b82e8f47912a2/lib/response.js#L4) we'd want to pass `settings.get('customFormats')` to avj's unknownFormats, ditto for [parameters.js](https://github.com/CacheControl/hippie-swagger/blob/74fa0280a444b78343d42f0f254b82e8f47912a2/lib/parameters.js#L4).  

If you'd like to take a crack at it, feel free.  Otherwise I'll get around to it when I have time.
